### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by starmun-0010** [muqsit-0010/Prune-Addon-FTB-Chunks#3]
- [ ] Better Command Chains (all parameters which make sense to be optional should be optional)
- [ ] For file types-> All Files and for dimensions-> All dimensions,argument values
- [ ] Prune claims where owner's/teams' last login was more than x days ago
- [ ] Compress Pruned files
- [ ] Configurable backup directories 
- [ ] Scheduled Auto Prune
